[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["julianferry94@gmail.com"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.1"
scikit-learn = "^0.22.2"
flask = "^1.1.1"
joblib = "^0.14.1"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
seaborn = "^0.10.0"
flake8 = "^3.7.9"
pytest = "^5.3.5"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
