[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["julianferry94@gmail.com"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
